fix: override of 'build.cssCodeSplit' will not take effect if `config.build.cssCodeSplit` is `undefined`
marco-prontera/vite-plugin-css-injected-by-js pull request #148
Opened 2024-09-12 11:25 UTC by voldikss

2024-09-13 06:43 UTC, marco-prontera requested changes
Thanks for your contribution! I think it is enough to change the code currently present in the repo with the first comment of this review and then we can proceed with the merge.

2024-09-13 06:43 UTC, marco-prontera commented on src/index.ts
> -                        if (config.build.cssCodeSplit == false) {
To fix what the title says it's enough to change this to: `if (!config.build.cssCodeSplit) {`

2024-09-13 06:43 UTC, marco-prontera commented on src/index.ts
> +                if (env.command === 'serve') return
This is not necessary as the modification must only be made if the command is 'build'

2024-09-13 06:43 UTC, marco-prontera commented on src/index.ts
> +                        cssCodeSplit: true
`return` isn't required

2024-09-13 07:28 UTC, voldikss commented
@marco-prontera PTAL

2024-09-27 04:50 UTC, voldikss commented
Hi @marco-prontera could this PR get merged?

2024-09-27 06:04 UTC, marco-prontera approved these changes

2024-09-27 06:06 UTC, merged